services:
  # PostgreSQL Service
  postgres:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: islem
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # PgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: islemharoun@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend

  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: mongod --setParameter authenticationMechanisms=SCRAM-SHA-1
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"  # Accès à mongo-express via http://localhost:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
    networks:
      - backend

  # Consul Service
  consul:
    image: hashicorp/consul:1.20.2
    container_name: consul
    restart: always
    ports:
      - "8500:8500"  # Port d'interface Web et API
    command: "consul agent -dev -client=0.0.0.0"  # Mode développement pour simplifier
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - backend

  # School Service
  school:
    build:
      context: ./school
      dockerfile: Dockerfile
    container_name: school
    restart: always
    ports:
      - "8002:8000"  # Port externe:interne
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    networks:
      - backend
    depends_on:
      - consul
      - postgres  # Ajout de la dépendance à postgres
    labels:
      - "consul.tags=school"
      - "consul.service.name=school"
      - "consul.service.port=8000"
      - "consul.service.address=school"
    command: >
      sh -c "sleep 10 && 
             consul services register -name=school -port=8000 -address=school &&
             php artisan serve --host=0.0.0.0 --port=8000"

  student:
    build:
      context: ./student
      dockerfile: Dockerfile
    container_name: student
    restart: always
    ports:
      - "8001:8000"
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
      - SCHOOL_SERVICE_URL=http://school:8000
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=db_mongo_service
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    networks:
      - backend
    depends_on:
      - consul
      - mongo
      - school
    labels:
      - "consul.tags=student"
      - "consul.service.name=student"
      - "consul.service.port=8000"
      - "consul.service.address=student"
    command: >
      sh -c "sleep 10 && 
             consul services register -name=student -port=8000 -address=student &&
             php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  local_pgdata:
    driver: local
  pgadmin_data:
    driver: local
  mongo_data:
    driver: local

networks:
  backend:
    driver: bridge
