services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"  # Lier le port 27018 (hôte) au port 27017 (conteneur)
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Accède à mongo-express via http://localhost:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
    networks:
      - backend

volumes:
  mongo_data:
    driver: local

networks:
  backend:
    driver: bridge
